vim.keymap.set('n', '<leader>t', '<CMD>FloatermNew --autoclose=1<CR>', options)
vim.keymap.set('t', '<leader>tp', '<C-n><CMD>FloatermPrev<CR>', options)
vim.keymap.set('t', '<leader>tn', '<C-n><CMD>FloatermNext<CR>', options)
vim.keymap.set('n', '<leader>tt', '<CMD>FloatermToggle<CR>', options)
vim.keymap.set('t', '<leader>tt', '<C-n><CMD>FloatermToggle<CR>', options)
vim.keymap.set('t', '<leader>tk', '<C-n><CMD>FloatermKill<CR>', options)
vim.keymap.set('n', '<leader>tka', '<CMD>FloatermKill!<CR>', options)
