vim.keymap.set('n', '<leader>ptt', '<CMD>FloatermNew --autoclose=1<CR>', options)
vim.keymap.set('n', '<leader>ptp', '<CMD>FloatermPrev<CR>', options)
vim.keymap.set('t', '<leader>ptp', '<C-n><CMD>FloatermPrev<CR>', options)
vim.keymap.set('n', '<leader>ptn', '<CMD>FloatermNext<CR>', options)
vim.keymap.set('t', '<leader>ptn', '<C-n><CMD>FloatermNext<CR>', options)
vim.keymap.set('n', '<leader>pt', '<CMD>FloatermToggle<CR>', options)
vim.keymap.set('t', '<leader>pt', '<C-n><CMD>FloatermToggle<CR>', options)
vim.keymap.set('t', '<leader>ptk', '<C-n><CMD>FloatermKill<CR>', options)
vim.keymap.set('n', '<leader>ptka', '<CMD>FloatermKill!<CR>', options)
